-- CREATE DATABASE AND TABLES 
DROP DATABASE IF EXISTS employees_db;
CREATE DATABASE employees_db;

USE employees_db;

-- DEPARTMENT TABLE 
CREATE TABLE department (
  id INT(11) PRIMARY KEY,
  name VARCHAR (30) NOT NULL,
);

-- ROLE TABLE 
CREATE TABLE role (
  id INT(11) AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR (30) NOT NULL,
  salary DECIMAL(10,0) NOT NULL,
  departmentID INT
);

-- EMPLOYEE TABLE 
CREATE TABLE employees (
  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  firstName VARCHAR (30) NOT NULL,
  lastName VARCHAR (30) NOT NULL,
  roleID INT,
  managerID INT
);


